import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";

const freesentaion = localFont({
    src: [
        {
            path: "../fonts/Freesentation-1Thin.ttf",
            weight: "100",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-2ExtraLight.ttf",
            weight: "200",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-3Light.ttf",
            weight: "300",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-4Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-5Medium.ttf",
            weight: "500",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-6SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-7Bold.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-8ExtraBold.ttf",
            weight: "800",
            style: "normal",
        },
        {
            path: "../fonts/Freesentation-9Black.ttf",
            weight: "900",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${freesentaion.className} h-lvh`}>
                <Header />
                <div className="p-2 pt-14 h-dvh-header">{children}</div>
            </body>
        </html>
    );
}
